name: Run Shell Script

on:
  workflow_dispatch:  # 手动触发
  schedule:           # 定时触发
    - cron: '0 0 * * *'  # 每天午夜 0 点触发（UTC 时间）

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          chmod +x ./start.sh  # 确保脚本是可执行的
          chmod +x ./cf_ddns/*.sh  # 确保脚本是可执行的
          ./start.sh > yxip.csv           # 运行脚本
          
      - name: Convert CSV to TXT and extract IP
        run: |
          awk -F, '{print $2}' yxip.csv > yxip.txt  # 提取第二列（IP 地址）并保存为 yxip.txt   
          
      - name: Commit yxips
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .          # 添加结果文件
          git commit -m "Update yxip.txt with latest output" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token 进行身份验证    
